**多项式回归**

尝试拟合如下多项式： 
$$y = 5 + 1.2x - 3.4\frac{x^2}{2!} + 5.6 \frac{x^3}{3!} + \epsilon \text{ where }
\epsilon \sim \mathcal{N}(0, 0.1^2).$$

In [1]:
import numpy as np

g_max_degree = 20
g_num_train, g_num_test = 100, 100
true_w = np.zeros(g_max_degree)
true_w[0:4] = np.array([5, 1.2, -3.4, 5.6])

In [4]:
import math

features = np.random.normal(size=(g_num_train + g_num_test, 1))
np.random.shuffle(features) # features 是自变量 x

poly_features = np.power(features, np.arange(g_max_degree).reshape(1, -1)) # 做对于x的指数
for i in range(g_max_degree):
    poly_features[:, i] /= math.gamma(i + 1) # 除以一个阶乘，避免数值爆炸
labels = np.dot(poly_features, true_w) # 乘上参数 w
labels += np.random.normal(scale=0.1, size=labels.shape)

In [7]:
import torch
true_w, features, poly_features, labels = [torch.tensor(x, dtype=
    torch.float32) for x in [true_w, features, poly_features, labels]]

features[:2], poly_features[:2, :], labels[:2]

(tensor([[-1.3624],
         [-0.7638]]),
 tensor([[ 1.0000e+00, -1.3624e+00,  9.2809e-01, -4.2148e-01,  1.4356e-01,
          -3.9117e-02,  8.8824e-03, -1.7288e-03,  2.9442e-04, -4.4569e-05,
           6.0721e-06, -7.5207e-07,  8.5386e-08, -8.9485e-09,  8.7083e-10,
          -7.9096e-11,  6.7351e-12, -5.3976e-13,  4.0855e-14, -2.9295e-15],
         [ 1.0000e+00, -7.6380e-01,  2.9169e-01, -7.4265e-02,  1.4181e-02,
          -2.1663e-03,  2.7576e-04, -3.0090e-05,  2.8728e-06, -2.4381e-07,
           1.8622e-08, -1.2930e-09,  8.2301e-11, -4.8355e-12,  2.6381e-13,
          -1.3433e-14,  6.4126e-16, -2.8811e-17,  1.2226e-18, -4.9147e-20]]),
 tensor([-2.3514,  2.7832]))